[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "yarn"]

[build.nixpacksPlan.phases.install]
cmds = ["yarn install --frozen-lockfile"]

[build.nixpacksPlan.phases.build]
cmds = [
  "yarn build",
  "npx medusa db:create --if-not-exists || true",
  "npx medusa db:migrate --run-migrations",
  "npx medusa links sync"
]

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"