[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "yarn"]

[build.nixpacksPlan.phases.install]
cmds = ["yarn install"]

[build.nixpacksPlan.phases.build]
cmds = [
  "yarn build", 
  "npx medusa db:setup --skip-migrations",
  "npx medusa db:migrate",
  "npx medusa links sync"
]

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300